######################################################################
# Automatically generated by qmake (1.07a) Tue Jan 22 08:13:26 2013
######################################################################

TEMPLATE = app
INCLUDEPATH += .
CONFIG += opengl
LIBS = -lglut

# Input
HEADERS += GLPanel.h GLTransform.h GUI.h
INTERFACES += myForm.ui
SOURCES += GLPanel.cpp GLTransform.cpp GUI.cpp main.cpp
